# -*- coding: utf-8 -*-
"""Question2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gLYfP4DXfnBb-nM9hKmIURIWRxadhXUk
"""

# 18-09-2023
# CSC461 – Assignment1 – Web Scraping
# Hamna Shahbaz
# Fa21-bse-048
# In the two parts of this question, i was succesfully able to retrieve the information on people who sahre my birthday.
#And in the second part i was supposed to get the details of all the important events coinciding with my birthday.
# Result: I was not able to execute the second taks because of the vast number of events occuring with different information.
# The same method was esecuted porperly on timeanddate.com but scraping from britannica.com proved tricky.
import requests
from bs4 import BeautifulSoup

#extracting births on 3rd August information from BeautifulSoup
response_1 = requests.get("https://www.timeanddate.com/on-this-day/august/3")
soup_date = BeautifulSoup(response_1.content, 'html5lib')
date_birth = soup_date.find('div', class_="otd-life__block")
unorderlist_birth = date_birth.find('ul', class_= "list--big")
list_item_birth = unorderlist_birth.find_all('li')

#create a file and put it in write mode
with open('Births3rdAug', "w", encoding = 'utf-8') as file:
  file.write("All births on 3rd August around the world with their years and descriptions\n\n")
#Loop through and write all the elements of list into the file
  for item in list_item_birth:
      file.write(item.text + '\n')
file.close()

#extracting events on 3rd August information from BeautifulSoup
response_2 = requests.get("https://www.britannica.com/on-this-day/August-3")
soup_event = BeautifulSoup(response_2.content, 'html5lib')
#information for featured event on 3rd August
class_fevent = soup_event.find('div', class_="otd-featured-event")
year_fevent = class_fevent.find('div', class_="date-label")
description_fevent = class_fevent.find('div', class_="title")

with open('Events3rdAug', "w", encoding = 'utf-8') as file:
  file.write("Featured Event of 3rd August:\n\n" + year_fevent.text + '\n\n')
  file.write(description_fevent.text + '\n')
file.close()

#information for normal events on 3rd August
#for events in soup_event:
#  class_event = soup_event.find('div', class_="border-top")
# year_event = class_event.find('div', class_="date-label")
#  description_event = class_event.find('div', class_="card-body")
#for i
# normal_event = year_event + description_event
#for yr in year_event:
#  print(yr.text)

#for desc in description_event:
#  print(desc.text)

